name: Second Continuous Deployment

# Only run this workflow once the Terraform Apply workflow has completed.
on:
  workflow_run:
    workflows: [Terraform Apply]
    types:
      - completed

# Only run one workflow at a time that has the `coordination-deploy` group.
concurrency:
  group: coordination-deploy

jobs:
  # Check if the terraform configuration was applied successfully.
  terraform-success:
    name: 'Terraform Successful'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The terraform configuration was applied successfully.'
  terraform-failure:
    name: 'Terraform Unsuccessful'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The terraform configuration could not be applied.'
  
  # Exit this workflow if the terraform configuration was applied successfully.
  exit:
    name: 'Exit'
    needs: terraform-failure
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  
  # Only run this workflow if files changed in the .github directory or respective project's directory.
  check_changes:
    name: 'Check Changes'
    needs: terraform-success
    runs-on: ubuntu-latest
    outputs:
      src:
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - '.github/**'
            - 'secondpath/**'
  
  set_environment:
    name: 'Set Environment'
    needs: check_changes
    runs-on: ubuntu-latest
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    steps:
      - id: setenv
        run: |
          if [ "${{github.ref_name}}" == "develop" ]; then 
            echo "my_env=Develop" >> "$GITHUB_OUTPUT";
          fi